import {
	Android,
	C,
	CSharp,
	DS,
	Php,
	Go,
	NodeJs,
	DevOps,
	Game,
	IOS,
	Java,
	ML,
	Python,
	Qa,
	Ruby,
	Rust,
	React,
	OneC,
	BASA,
} from '../assets';
import { Media } from '../types/media';

export const mediaLinks: Media[] = [
	{
		title: 'Python Developer',
		link: 'https://t.me/+ESvCF1T89XNkOWYy',
		specializations: [19],
		image: Python,
	},
	{
		title: 'C# Developer',
		link: 'https://t.me/+IiB9MdbGUOxmNzli',
		specializations: [33],
		image: CSharp,
	},
	{
		title: 'ML Engineer',
		link: 'https://t.me/+DbMQbphRGt0xNTU6',
		specializations: [37],
		image: ML,
	},
	{
		title: 'C/C++ Developer',
		link: 'https://t.me/+Z9wqIOFdHbkyYzQy',
		specializations: [32],
		image: C,
	},
	{
		title: 'Data Science',
		link: 'https://t.me/+dnZMFajHMqkyZTky',
		specializations: [34],
		image: DS,
	},
	{
		title: 'Java Developer',
		link: 'https://t.me/+4kGLlFfiWWBhZTc6',
		specializations: [20],
		image: Java,
	},
	{
		title: 'PHP Developer',
		link: 'https://t.me/+ny_6GvV684cwOGM6',
		specializations: [24],
		image: Php,
	},
	{
		title: 'React Developer',
		link: 'https://t.me/+_hfo9fzcFNxiY2Fi',
		specializations: [11],
		image: React,
	},
	{
		title: 'Rust Developer',
		link: 'https://t.me/+qZZcP2_m_UNlOWQ6',
		specializations: [28],
		image: Rust,
	},
	{
		title: 'Golang Developer',
		link: 'https://t.me/+NFCSAsCPBa9kOWQy',
		specializations: [23],
		image: Go,
	},
	{
		title: 'Ruby Developer',
		link: 'https://t.me/+w_hDI2z7uEcwZDMy',
		specializations: [25],
		image: Ruby,
	},
	{
		title: 'Node.js Developer',
		link: 'https://t.me/+y__haOJn5K8zZDgy',
		specializations: [21],
		image: NodeJs,
	},
	{
		title: 'QA Engineer',
		link: 'https://t.me/+4Wv3cw34AXZiZTQ6',
		specializations: [29],
		image: Qa,
	},
	{
		title: 'Android Developer',
		link: 'https://t.me/+3sIlHYjfoAU1MDA6',
		specializations: [27],
		image: Android,
	},
	{
		title: 'iOS Developer',
		link: 'https://t.me/+TcGolYjIcjQ3MWJi',
		specializations: [26],
		image: IOS,
	},
	{
		title: 'Game Developer',
		link: 'https://t.me/+mCRECMm9HUFiMzQy',
		specializations: [35],
		image: Game,
	},
	{
		title: 'DevOps Engineer',
		link: 'https://t.me/+YTy2aTPQGSpmY2My',
		specializations: [36],
		image: DevOps,
	},
	{
		title: 'Analysis (BA/SA)',
		link: 'https://t.me/+lxcCUoFaROczNjUy',
		specializations: [42, 44],
		image: BASA,
	},
	{
		title: '1C',
		link: 'https://t.me/+OckfmVa0MvJlMGQy',
		specializations: [41, 43],
		image: OneC,
	},
];
