#syntax=docker/dockerfile:1

# Стадия сборки
FROM node:20-alpine as builder

WORKDIR /app

# Скопировать файлы `package.json` и `package-lock.json` (или `yarn.lock`)
COPY package.json package-lock.json ./

# Установить зависимости
RUN npm ci

# Скопировать все файлы проекта в рабочую директорию
COPY . .

# Добавить аргументы сборки
ARG API_URL
ARG LANDING_URL
ARG PORT
ARG NODE_ENV
ARG SENTRY_DSN
ARG TBANK_API_HOST
ARG TBANK_TERMINAL_KEY
ARG TBANK_TERMINAL_PASS

# Установить переменные окружения
ENV API_URL=$API_URL
ENV LANDING_URL=$LANDING_URL
ENV PORT=$PORT
ENV NODE_ENV=$NODE_ENV
ENV SENTRY_DSN=$SENTRY_DSN
ENV TBANK_API_HOST=$TBANK_API_HOST
ENV TBANK_TERMINAL_KEY=$TBANK_TERMINAL_KEY
ENV TBANK_TERMINAL_PASS=$TBANK_TERMINAL_PASS

# Вывести переменные окружения для отладки
RUN echo "API_URL: $API_URL"
RUN echo "LANDING_URL: $LANDING_URL"
RUN echo "PORT: $PORT"
RUN echo "NODE_ENV: $NODE_ENV"
RUN echo "SENTRY_DSN: $SENTRY_DSN"
RUN echo "TBANK_API_HOST: $TBANK_API_HOST"
RUN echo "TBANK_TERMINAL_KEY: $TBANK_TERMINAL_KEY"
RUN echo "TBANK_TERMINAL_PASS: $TBANK_TERMINAL_PASS"

# Собрать приложение
RUN npm run build

# Стадия запуска с Nginx
FROM nginx:stable-alpine

# Копировать собранные файлы в контейнер Nginx
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]
