name: Deploy Platform

on:
  push:
    branches:
      - develop
      - main

env:
  SERVICE_NAME_PRODUCTION: platform
  REGISTRY: cr.selcloud.ru/yeahub-registry
  IMAGE_NAME: yeahub-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref == 'refs/heads/develop' && 'deploy-develop' || github.run_id }}
      cancel-in-progress: ${{ github.ref == 'refs/heads/develop' && true || false }}
    steps:
      # ================== VPS ==================
      - name: Deploy to VPS for production
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST_PRODUCTION }}
          username: ${{ secrets.VPS_USERNAME_PRODUCTION }}
          key: ${{ secrets.VPS_SSH_KEY_PRODUCTION }}
          script: |
            docker-compose --env-file .env.production up -d --build ${{ env.SERVICE_NAME_PRODUCTION }}

      # ================== KUBERNETES (develop) ==================
      - name: Build and push Docker image
        if: github.ref == 'refs/heads/develop'
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login cr.selcloud.ru -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA} \
            --build-arg API_URL="https://api.yeatwork.ru/" \
            --build-arg LANDING_URL="https://yeatwork.ru/" \
            --build-arg PORT=5173 \
            --build-arg NODE_ENV=production \
            --build-arg SENTRY_DSN="${{ secrets.SENTRY_DSN }}" \
            --build-arg TELEGRAM_BOT_NAME="yeahub_test_bot" \
            .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}

      - name: Checkout Helm repo
        if: github.ref == 'refs/heads/develop'
        uses: actions/checkout@v3
        with:
          repository: YeaHubTeam/yeahub-helm
          token: ${{ secrets.HELM_REPO_TOKEN || secrets.GITHUB_TOKEN }}
          path: helm

      - name: Update image tag in values-test.yaml
        if: github.ref == 'refs/heads/develop'
        run: |
          yq eval ".frontend.tag = \"${GITHUB_SHA}\"" -i helm/values-test.yaml

      - name: Commit and push Helm changes
        if: github.ref == 'refs/heads/develop'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update frontend tag to ${GITHUB_SHA}'
          branch: develop
          file_pattern: 'values-test.yaml'
          repository: helm
