const keywordTitleOverrides: Record<string, string> = {
	ai: 'AI',
	api: 'API',
	bash: 'Bash',
	'c++': 'C++',
	'ci/cd': 'CI/CD',
	clickhouse: 'ClickHouse',
	css: 'CSS',
	devops: 'DevOps',
	django: 'Django',
	'django framework': 'Django Framework',
	'django rest framework': 'Django REST Framework',
	docker: 'Docker',
	eslint: 'ESLint',
	fastapi: 'FastAPI',
	figma: 'Figma',
	flask: 'Flask',
	git: 'Git',
	gitlab: 'GitLab',
	grafana: 'Grafana',
	grpc: 'gRPC',
	http: 'HTTP',
	javascript: 'JavaScript',
	jira: 'Jira',
	kubernetes: 'Kubernetes',
	linux: 'Linux',
	llm: 'LLM',
	mongodb: 'MongoDB',
	'next.js': 'Next.js',
	ооп: 'ООП',
	pandas: 'Pandas',
	postgresql: 'PostgreSQL',
	prometheus: 'Prometheus',
	pytest: 'Pytest',
	python: 'Python',
	pytorch: 'PyTorch',
	rabbitmq: 'RabbitMQ',
	react: 'React',
	redis: 'Redis',
	rest: 'REST',
	'rest api': 'REST API',
	sentry: 'Sentry',
	solid: 'SOLID',
	sql: 'SQL',
	sqlalchemy: 'SQLAlchemy',
	storybook: 'Storybook',
	typescript: 'TypeScript',
	vue: 'Vue',
	webpack: 'Webpack',
};

export const formatKeywordTitle = (keywordTitle: string) =>
	keywordTitleOverrides[keywordTitle.trim().toLocaleLowerCase('en-US')] ?? keywordTitle;
